[env]
TERM = "alacritty"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
style = "SemiBold"

[font.italic]
style = "Regular"

[font.bold_italic]
style = "SemiBold"

[colors.primary]
background = "#111111"
foreground = "#e0e0e0"

[colors.cursor]
cursor = "#e0e0e0"
text = "#111111"

[colors.normal]
black = "#111111"
red = "#cc6666"
green = "#99cc99"
yellow = "#f8fe7a"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#e0e0e0"
